// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlkl0S_3JaApQ4khXyaqIK0J0ZArGuNpg',
    appId: '1:279196897707:web:30b4ef9cae07d6a4c742ee',
    messagingSenderId: '279196897707',
    projectId: 'mindreset-f15f3',
    authDomain: 'mindreset-f15f3.firebaseapp.com',
    storageBucket: 'mindreset-f15f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-spmCyYJLihwD7MfzBmxbeXHnWdjRQhs',
    appId: '1:279196897707:android:6fca533039fd6dcbc742ee',
    messagingSenderId: '279196897707',
    projectId: 'mindreset-f15f3',
    storageBucket: 'mindreset-f15f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsqp8g3hfV8PQulN0Wvk61E6fTXm_5bFQ',
    appId: '1:279196897707:ios:5418f58df12c88cbc742ee',
    messagingSenderId: '279196897707',
    projectId: 'mindreset-f15f3',
    storageBucket: 'mindreset-f15f3.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsqp8g3hfV8PQulN0Wvk61E6fTXm_5bFQ',
    appId: '1:279196897707:ios:5418f58df12c88cbc742ee',
    messagingSenderId: '279196897707',
    projectId: 'mindreset-f15f3',
    storageBucket: 'mindreset-f15f3.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlkl0S_3JaApQ4khXyaqIK0J0ZArGuNpg',
    appId: '1:279196897707:web:d9e5a1d5f5519720c742ee',
    messagingSenderId: '279196897707',
    projectId: 'mindreset-f15f3',
    authDomain: 'mindreset-f15f3.firebaseapp.com',
    storageBucket: 'mindreset-f15f3.firebasestorage.app',
  );
}

